### ISSUE TITLE
Throwing error `Requiring unknown module "react"`

### ISSUE THREAD

**Issue by gapl** [ide/react-clone-referenced-element#3]
When including this module in my react native application, it is throwing the above error - `Requiring unknown module "react"`. I am using react-native v0.18.0.

I did some further research and module `react` is included in `./node_modules/react-native/node_modules/react` whereas module `react-clone-referenced-element` resides in `./node_modules/react-clone-referenced-element`. If I manually add `react` module to my project there are then of course conflicts with doubled class names (as react is added as my project's dependency and as react-native's dependency).

**Comment by richardtreichel** [comment]
I've had similar issues while trying to use [ExNavigator](https://github.com/exponentjs/ex-navigator) with React Native.

Upgrading to npm v3 seemed to help with the unknown module error, but unless I manually change [this line](https://github.com/ide/react-clone-referenced-element/blob/master/cloneReferencedElement.js#L3) to `require('react-native')` instead of `require('react')`, I get the following error:
`_registerComponent(...): Target container is not a DOM element.`

**Comment by ide** [comment]
npm 3 fixes this or you can wait for the next release of RN.
